import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { cacheRoot, loadMeta, type ResortEntry } from '../../src/lib/data';
import type { Resolved } from '../../src/schema/meta';

const RESOLVED_FIELDS: (keyof Resolved)[] = ['address', 'country', 'website', 'googlePlaceId', 'wikidataId'];

/** data/cache/_report.md. No timestamps, so an unchanged cache gives an unchanged report. */
export function writeReport(resorts: ResortEntry[], failures: Map<string, string>): void {
  const lines = [
    '# Data report',
    '',
    'Generated by `npm run fetch`. Lists what could not be found, so you know what to fill in by hand.',
    '',
    '| Resort | Resolved as | Source | Confidence | Missing |',
    '| --- | --- | --- | --- | --- |',
  ];
  const details: string[] = [];

  for (const r of resorts) {
    const meta = loadMeta(r.slug);
    const failure = failures.get(r.slug);
    if (!meta) {
      lines.push(`| ${r.name} | **not resolved** | | | everything |`);
      if (failure) details.push(`## ${r.name}`, '', '```', failure, '```', '');
      continue;
    }
    const missing = RESOLVED_FIELDS.filter((k) => meta.resolved[k] == null);
    lines.push(
      `| ${r.name} | ${meta.resolved.name} | ${meta.provider} | ${meta.confidence} | ${missing.join(', ') || '-'} |`,
    );
    if (meta.alternatives.length || failure) {
      details.push(`## ${r.name}`, '');
      if (failure) details.push('Last refresh failed, previous data kept:', '', '```', failure, '```', '');
      if (meta.alternatives.length) {
        details.push('Other matches considered:', '');
        for (const a of meta.alternatives) details.push(`- ${a.name} (${a.provider}, ${a.confidence})`);
        details.push('');
      }
    }
  }
  writeFileSync(join(cacheRoot, '_report.md'), `${[...lines, '', ...details].join('\n').trimEnd()}\n`);
}
