import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { cacheRoot, loadMeta, loadTravel, loadWeather, type ResortEntry } from '../../src/lib/data';
import { loadFacts } from '../../src/lib/facilities';
import { FIELDS } from '../../src/schema/facility-fields';
import type { Resolved } from '../../src/schema/meta';
import fr from '../../src/i18n/fr.json';

const RESOLVED_FIELDS: (keyof Resolved)[] = ['address', 'country', 'website'];
const label = (key: string) => (fr.fields as Record<string, string>)[key] ?? key;
const VERIFY_BELOW = 0.6;

/** data/overrides/_template.yml: every key you can set by hand, generated from the field registry. */
export function writeOverrideTemplate(): void {
  const lines = [
    '# Copy the lines you need into data/overrides/<slug>.yml. Hand-written values always win over fetched data.',
    '# `null` hides a fetched value you know is wrong. This file is generated by `npm run fetch`; do not edit.',
    '',
    '# airport: VRA          # arrival airport, when the nearest one has no flights from YUL',
    '# note: "Texte libre affiché sur la page de l\'hôtel"',
  ];
  for (const f of FIELDS) {
    const hint = f.type === 'enum' ? f.options!.join(' | ') : f.type === 'list' ? 'list of text' : f.type === 'number' ? `number${f.unit ? ` (${f.unit})` : ''}` : f.type === 'bool' ? 'true | false' : 'text';
    lines.push(`# ${f.key}:`.padEnd(32) + `# ${label(f.key)} - ${hint}`);
  }
  writeFileSync(join(process.cwd(), 'data', 'overrides', '_template.yml'), `${lines.join('\n')}\n`);
}

/** data/cache/_report.md. No timestamps, so an unchanged cache gives an unchanged report. */
export function writeReport(resorts: ResortEntry[], failures: Map<string, string>): void {
  const out = [
    '# Data report',
    '',
    'Generated by `npm run fetch`. Lists what could not be found, so you know exactly what to fill in by hand.',
    'Put hand-written facts in `data/overrides/<slug>.yml` (see `data/overrides/_template.yml` for every key).',
    '',
    '| Resort | Resolved as | Confidence | Facts found | Missing | To verify |',
    '| --- | --- | --- | --- | --- | --- |',
  ];
  const details: string[] = [];

  for (const r of resorts) {
    const meta = loadMeta(r.slug);
    const failure = failures.get(r.slug);
    if (!meta) {
      out.push(`| ${r.name} | **not resolved** | | | | |`);
      if (failure) details.push(`## ${r.name}`, '', '```', failure, '```', '');
      continue;
    }
    const facts = loadFacts(r);
    const found = FIELDS.filter((f) => facts.fields[f.key]);
    const missing = FIELDS.filter((f) => !facts.fields[f.key]);
    const verify = found.filter((f) => facts.fields[f.key]!.confidence <= VERIFY_BELOW && facts.fields[f.key]!.source !== 'override');
    out.push(`| ${r.name} | ${meta.resolved.name} | ${meta.confidence} | ${found.length}/${FIELDS.length} | ${missing.length} | ${verify.length} |`);

    details.push(`## ${r.name} (\`${r.slug}\`)`, '');
    if (failure) details.push('Last refresh failed, previous data kept:', '', '```', failure, '```', '');
    const noResolved = RESOLVED_FIELDS.filter((k) => meta.resolved[k] == null);
    if (noResolved.length) details.push(`- Identity not found: ${noResolved.join(', ')}`);
    const weather = loadWeather(r.slug);
    const travel = loadTravel(r.slug);
    if (!weather) details.push('- Weather: missing');
    else if (weather.summary.seaTemp == null) details.push('- Sea temperature: not available for this location');
    if (!travel) details.push('- Travel: missing');
    else {
      if (travel.flight.estimated) details.push(`- Flight time is an estimate: add ${travel.airport.iata} to data/reference/flight-times.yml`);
      if (travel.transfer.estimated) details.push('- Transfer time is an estimate (routing failed)');
    }
    if (r.price_cad == null) details.push('- Price: add `price_cad` to data/resorts.yml (total per person for the stay)');
    if (verify.length) details.push(`- To verify (low confidence): ${verify.map((f) => f.key).join(', ')}`);
    details.push(`- Missing facts (${missing.length}): ${missing.map((f) => f.key).join(', ') || 'none'}`);
    if (meta.alternatives.length) details.push(`- Other matches considered: ${meta.alternatives.map((a) => `${a.name} (${a.provider}, ${a.confidence})`).join('; ')}`);
    details.push('');
  }
  writeFileSync(join(cacheRoot, '_report.md'), `${[...out, '', ...details].join('\n').trimEnd()}\n`);
}
